export const TOOL_DESCRIPTIONS: Record<string, string> = {
  time_now: 'Trenutno vreme i datum.',
  reminders_create: 'Kreiraj podsetnik u Apple Reminders.',
  reminders_list: 'Listaj aktivne podsetnike.',
  calendar_today: 'Današnji događaji iz Apple kalendara.',
  open_app: 'Otvori macOS aplikaciju.',
  open_url: 'Otvori URL u browseru.',
  web_search: 'Web pretraga (DuckDuckGo).',
  read_clipboard: 'Pročitaj sistemski clipboard.',
  write_clipboard: 'Zapiši tekst u clipboard.',
  system_volume: 'Podesi zvuk sistema.',
  ytm_play: 'Pusti pesmu u YouTube Music.',
  ytm_pause: 'Pauziraj YouTube Music.',
  ytm_resume: 'Nastavi YouTube Music.',
  ytm_next: 'Sledeća pesma (YTM).',
  ytm_previous: 'Prethodna pesma (YTM).',
  ytm_volume_set: 'Postavi jačinu samo u YT Music playeru.',
  ytm_volume_up: 'Pojačaj samo YT Music player.',
  ytm_volume_down: 'Smanji samo YT Music player.',
  ytm_volume_mute: 'Utišaj samo YT Music player.',
  ytm_status: 'Verifikovan status reprodukcije (šta svira + YTM).',
  play_youtube: 'Pusti YouTube video u Chrome-u.',
  kilo_run: 'Pokreni kod/terminal zadatak preko Kilo Code agenta.',
};

export const TOOL_PARAMS: Record<string, string[]> = {
  time_now: [],
  reminders_create: ['title', 'list', 'due_iso'],
  reminders_list: ['list', 'limit'],
  calendar_today: ['calendar'],
  open_app: ['name'],
  open_url: ['url', 'browser'],
  web_search: ['query', 'max_results'],
  read_clipboard: [],
  write_clipboard: ['text'],
  system_volume: ['level', 'mute'],
  ytm_play: ['query'],
  ytm_pause: [],
  ytm_resume: [],
  ytm_next: [],
  ytm_previous: [],
  ytm_volume_set: ['level'],
  ytm_volume_up: ['amount'],
  ytm_volume_down: ['amount'],
  ytm_volume_mute: [],
  ytm_status: [],
  play_youtube: ['query'],
  kilo_run: ['prompt', 'cwd', 'max_duration_s'],
};
